# Generated by Django 6.0.2 on 2026-02-12 09:14

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload a profile image (optional)', null=True, upload_to=accounts.models.user_profile_image_path),
        ),
    ]
