# Generated by Django 4.2.27 on 2026-02-12 09:49

from django.db import migrations


def set_superuser_roles(apps, schema_editor):
    """Set existing superusers to SUPER_ADMIN role"""
    CustomUser = apps.get_model('accounts', 'CustomUser')
    CustomUser.objects.filter(is_superuser=True).update(role='SUPER_ADMIN')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_state_customuser_role_statepermission'),
    ]

    operations = [
        migrations.RunPython(set_superuser_roles, reverse_code=migrations.RunPython.noop),
    ]
