# Generated by Django 4.2.27 on 2026-02-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_set_superuser_roles'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='custom_user_role_aeef4e_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active', 'role'], name='custom_user_is_acti_bc0a27_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['is_active'], name='accounts_st_is_acti_608656_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['code'], name='accounts_st_code_f99299_idx'),
        ),
    ]
