# Generated by Django 4.2.27 on 2026-02-13 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_custom_user_role_aeef4e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'division',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='accounts.division')),
            ],
            options={
                'db_table': 'product',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Stockist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockists', to='accounts.state')),
            ],
            options={
                'db_table': 'stockist',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StockistProductMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField()),
                ('month_year', models.CharField(db_index=True, max_length=20)),
                ('pdf_division', models.CharField(blank=True, max_length=100)),
                ('pdf_product', models.CharField(blank=True, max_length=200)),
                ('pdf_closing', models.IntegerField(default=0)),
                ('excel_closing', models.IntegerField(default=0)),
                ('match_method', models.CharField(blank=True, choices=[('EXACT', 'Exact'), ('FUZZY', 'Fuzzy Match')], max_length=20)),
                ('variance', models.IntegerField(default=0)),
                ('validation', models.CharField(choices=[('MATCHED', 'Matched'), ('QUANTITY_MISMATCH', 'Quantity Mismatch'), ('DIVISION_MISMATCH', 'Division Mismatch'), ('QUANTITY_AND_DIVISION_MISMATCH', 'Quantity and Division Mismatch'), ('PRODUCT_NOT_FOUND', 'Product Not Found')], db_index=True, max_length=50)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('excel_division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.division')),
                ('excel_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.product')),
                ('stockist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_matches', to='accounts.stockist')),
            ],
            options={
                'db_table': 'stockist_product_match',
                'ordering': ['-month_year', 'stockist', 'row_index'],
                'indexes': [models.Index(fields=['stockist', 'month_year'], name='stockist_pr_stockis_cd1cbe_idx'), models.Index(fields=['validation', 'month_year'], name='stockist_pr_validat_c2e76e_idx'), models.Index(fields=['month_year', 'stockist', 'row_index'], name='stockist_pr_month_y_a147ac_idx')],
                'unique_together': {('stockist', 'month_year', 'row_index')},
            },
        ),
        migrations.AddIndex(
            model_name='stockist',
            index=models.Index(fields=['state', 'is_active'], name='stockist_state_i_59756a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['division', 'is_active'], name='product_divisio_121420_idx'),
        ),
    ]
